# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  lh_FFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_FFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_FFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_FFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_LFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_LFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_LFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_LFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_LFJ5:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_MFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_MFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_MFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_MFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_RFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_RFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_RFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_RFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_THJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_THJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  lh_THJ3:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  lh_THJ4:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  lh_THJ5:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ5:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ3:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ4:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ5:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0